
export enum SVGIconEnum {
  COMPANIES,
  DASHBOARD,
  PERSON,
  DROPDOWNARROW,
  MENU,
  CALENDAR,
  RIDE,
  REPORTS,
  MAIN,
  DIVIDER,
  STAR,
  QUALITYSTARS,
  ROAD,
  TICK,
  X
}

export const SVGIconMAPPER = {
  COMPANIES: SVGIconEnum.COMPANIES,
  DASHBOARD: SVGIconEnum.DASHBOARD,
  PERSON: SVGIconEnum.PERSON,
  DROPDOWNARROW: SVGIconEnum.DROPDOWNARROW,
  MENU: SVGIconEnum.MENU,
  CALENDAR: SVGIconEnum.CALENDAR,
  RIDE: SVGIconEnum.RIDE,
  REPORTS: SVGIconEnum.REPORTS,
  MAIN: SVGIconEnum.MAIN,
  DIVIDER: SVGIconEnum.DIVIDER,
  STAR: SVGIconEnum.STAR,
  QUALITYSTARS: SVGIconEnum.QUALITYSTARS,
  ROAD: SVGIconEnum.ROAD,
  TICK: SVGIconEnum.TICK,
  X: SVGIconEnum.X
};
