
export enum SVGIconEnum {
  COMPANIES,
  DASHBOARD,
  PERSON,
  DROPDOWNARROW,
  MENU,
  CALENDAR,
  RIDE,
  REPORTS,
  MAIN,
  DIVIDER,
  STAR,
  QUALITYSTARS,
  ROAD,
  TICK,
  X,
  SETTINGS,
<<<<<<< HEAD
  LOGOUT,
  ARROW
=======
  LOGOUT
>>>>>>> dcf1e1754237864fd3b23f503c5e0a432b417f11
}

export const SVGIconMAPPER = {
  COMPANIES: SVGIconEnum.COMPANIES,
  DASHBOARD: SVGIconEnum.DASHBOARD,
  PERSON: SVGIconEnum.PERSON,
  DROPDOWNARROW: SVGIconEnum.DROPDOWNARROW,
  MENU: SVGIconEnum.MENU,
  CALENDAR: SVGIconEnum.CALENDAR,
  RIDE: SVGIconEnum.RIDE,
  REPORTS: SVGIconEnum.REPORTS,
  MAIN: SVGIconEnum.MAIN,
  DIVIDER: SVGIconEnum.DIVIDER,
  STAR: SVGIconEnum.STAR,
  QUALITYSTARS: SVGIconEnum.QUALITYSTARS,
  ROAD: SVGIconEnum.ROAD,
  TICK: SVGIconEnum.TICK,
  X: SVGIconEnum.X,
  SETTINGS: SVGIconEnum.SETTINGS,
<<<<<<< HEAD
  LOGOUT: SVGIconEnum.LOGOUT,
  ARROW: SVGIconEnum.ARROW
=======
  LOGOUT: SVGIconEnum.LOGOUT
>>>>>>> dcf1e1754237864fd3b23f503c5e0a432b417f11
};
